Repository RaphaZ99/skymed-mobile, pull requests merged in 2021-06, with the labels that each got.

#28 Ajustes de métodos HTTP
  lib/provider/base_http.dart
  lib/provider/pacientes.dart
  lib/views/auth_home_screen.dart
  lib/views/login.dart
  lib/views/menu-usuario.dart
Labels: Ajuste de erros/defeitos

#29 Adiciona métodos get put e delete
  lib/model/endereco.dart
  lib/model/especialidade.dart
  lib/model/hospital.dart
  lib/model/medico.dart
  lib/model/paciente.dart
  lib/model/usuario.dart
  lib/provider/base_http.dart
  lib/provider/medicos.dart
  lib/provider/pacientes.dart
  lib/views/listagem-medicos.dart
Labels: Implementação

#30 Implementacao edicao cadastro paciente
  lib/model/endereco.dart
  lib/model/medico.dart
  lib/model/paciente.dart
  lib/model/usuario.dart
  lib/provider/base_http.dart
  lib/provider/medicos.dart
  lib/provider/pacientes.dart
  lib/views/edicao-paciente-dados.dart
  lib/views/edicao-paciente-endereco.dart
  lib/views/listagem-medicos.dart
Labels: Ajuste de erros/defeitos, Ajuste de layout, Implementação

#31 Ordenacao filtragem medicos
  lib/model/dto_filtros_medico.dart
  lib/model/endereco.dart
  lib/model/especialidade.dart
  lib/model/horario_consulta.dart
  lib/model/horario_trabalho.dart
  lib/model/hospital.dart
  lib/model/medico.dart
  lib/model/paciente.dart
  lib/model/usuario.dart
  lib/provider/medicos.dart
  lib/views/agendamento-consulta.dart
  lib/views/listagem-medicos.dart
  lib/widgets/componentes/card-campo/campo.dart
  lib/widgets/componentes/listagem/card-medico.dart
  lib/widgets/componentes/modal/modal-consulta.dart
  lib/widgets/componentes/modal/modal-filtros.dart
  lib/widgets/componentes/modal/modal-ordenacao.dart
Labels: Ajuste de erros/defeitos, Implementação

#32 Implementa historico
  lib/model/dto_consultaComMedico.dart
  lib/model/dto_medicoComHospital.dart
  lib/model/especialidade.dart
  lib/model/horario_consulta.dart
  lib/model/horario_trabalho.dart
  lib/model/hospital.dart
  lib/model/medico.dart
  lib/provider/base_http.dart
  lib/provider/medicos.dart
  lib/views/agendamento-consulta.dart
  lib/views/historico-consultas.dart
  lib/views/listagem-medicos.dart
  lib/widgets/componentes/listagem/card-consulta.dart
  lib/widgets/componentes/listagem/card-medico.dart
  lib/widgets/componentes/modal/modal-confirmacao.dart
  lib/widgets/componentes/modal/modal-erro.dart
  lib/widgets/componentes/modal/modal-sucesso.dart
Labels: Implementação

#34 Ajuste gerais
  lib/model/endereco.dart
  lib/provider/base_http.dart
  lib/provider/pacientes.dart
  lib/views/cadastro-paciente-form-dados_senha.dart
  lib/views/cadastro-paciente-form_dados_endereco.dart
  lib/views/cadastro_paciente_form_dados_pessoais.dart
  lib/views/edicao-paciente-dados.dart
  lib/views/edicao-paciente-endereco.dart
  lib/views/login.dart
  lib/views/recuperar-senha-paciente-informar-email.dart
  lib/views/recuperar-senha-paciente-nova-senha.dart
Labels: Ajuste de erros/defeitos, Ajuste de layout, Criação de layout

#35 Ajusta agendamento
  lib/model/endereco.dart
  lib/model/especialidade.dart
  lib/provider/base_http.dart
  lib/provider/medicos.dart
  lib/provider/pacientes.dart
  lib/views/agendamento-consulta.dart
  lib/views/historico-consultas.dart
  lib/views/menu-usuario.dart
  lib/widgets/componentes/listagem/card-consulta.dart
  lib/widgets/componentes/listagem/card-medico.dart
Labels: Ajuste de erros/defeitos
